name: 🐛 Bug Report
description: Create a report to help us improve Sayf AI Text Fixer
title: "[BUG] "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🙏
        
        **Before submitting, please:**
        - Search existing issues to avoid duplicates
        - Make sure you're using the latest version
        - Test with a fresh API key if the issue is API-related

  - type: textarea
    id: description
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Open the application
        2. Select text '...'
        3. Press Ctrl+Alt+S
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: ❌ Actual Behavior
      description: What actually happened
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: 🔧 Version
      description: Which version of Sayf AI Text Fixer are you using?
      options:
        - v4.5.0 (Latest)
        - v4.0.8
        - v3.1.0
        - v3.0.0
        - v2.9.1
        - v2.9.0
        - v2.0.x
        - v1.5.x
        - Other (specify in additional context)
        - Development/Pre-release version
    validations:
      required: true

  - type: dropdown
    id: windows
    attributes:
      label: 🖥️ Windows Version
      description: Which Windows version are you using?
      options:
        - Windows 11
        - Windows 10
        - Other (specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: ai-mode
    attributes:
      label: 🤖 AI Processing Mode
      description: Which mode were you using when the bug occurred?
      options:
        - Fix
        - Improve
        - Rewrite
        - Answer
        - Summarize
        - Translate
        - Simplify
        - Longer
        - Shorter
        - Prompter
        - Formalize
        - Casual
        - Email
        - Bullets
        - Focus
        - Technical
        - Creative
        - Academic
        - Humanizer
        - Not applicable
        - Multiple modes
        - All modes affected

  - type: dropdown
    id: language
    attributes:
      label: 🌍 Text Language
      description: What language was the text you were processing?
      options:
        - English
        - Arabic
        - Mixed (Arabic + English)
        - Other
        - Not applicable

  - type: textarea
    id: error-messages
    attributes:
      label: 🚨 Error Messages
      description: Any error messages or log entries
      placeholder: Paste any error messages, dialog text, or relevant log entries here
      render: text

  - type: textarea
    id: logs
    attributes:
      label: 📋 Log Files
      description: Relevant log entries (if available)
      placeholder: |
        Check %AppData%\SayfTextFixer\SayfTextFixer_log.txt for relevant entries
        Paste the last few lines around the time the error occurred
      render: text

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Screenshots (if helpful)
        - What you were trying to accomplish
        - When the problem started
        - Any workarounds you've found
        - Other applications that might be interfering

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: Please confirm before submitting
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I am using the latest version available
          required: true
        - label: I have provided all required information
          required: true
        - label: I can reproduce this issue consistently
          required: true