blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/zSayf/SayfAiTextFixer/discussions
    about: Ask questions, share ideas, and discuss the project with the community
  - name: 📖 Documentation
    url: https://github.com/zSayf/SayfAiTextFixer/blob/main/README.md
    about: Check the comprehensive documentation and user guide
  - name: 🔒 Security Issues
    url: https://github.com/zSayf/SayfAiTextFixer/security/advisories/new
    about: Report security vulnerabilities privately