name: ✨ Feature Request
description: Suggest a new feature or enhancement for Sayf AI Text Fixer
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 🚀
        
        **Before submitting, please:**
        - Search existing feature requests to avoid duplicates
        - Consider if this fits with the tool's core purpose
        - Think about how this would benefit other users

  - type: textarea
    id: problem
    attributes:
      label: 🎯 Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Describe the problem or limitation you're experiencing.
        Example: "I often need to convert text to different writing styles but have to use multiple tools..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: Describe your ideal solution
      placeholder: |
        Describe how you envision this feature working.
        Be as specific as possible about the user experience.

  - type: dropdown
    id: category
    attributes:
      label: 📂 Feature Category
      description: What type of feature is this?
      options:
        - New AI Processing Mode (beyond current 18 modes)
        - Enhancement to Existing Mode
        - User Interface/UX Enhancement
        - Language/Localization Support
        - Performance Improvement
        - Integration Feature (other apps/services)
        - Configuration/Settings Enhancement
        - Accessibility Feature
        - Security Enhancement
        - API/Model Support (new AI providers)
        - Export/Import Features
        - Advanced Language Detection
        - Workflow Automation
        - Other

  - type: dropdown
    id: priority
    attributes:
      label: ⚡ Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Significantly impacts my usage
        - Critical - Blocking my use of the tool

  - type: textarea
    id: use-cases
    attributes:
      label: 🎭 Use Cases
      description: Describe specific scenarios where this feature would be useful
      placeholder: |
        Example scenarios (be specific about current limitations):
        1. When writing academic papers, I need to... (which current mode doesn't fully address)
        2. For social media content, it would help if... (beyond current Casual mode)
        3. In professional emails, this would allow me to... (enhancement to Email mode)
        4. For technical documentation, I wish I could... (beyond current Technical mode)
        5. When working with mixed languages, I need... (enhancement to current bilingual support)
        6. For creative writing, it would be useful to... (beyond current Creative mode)

  - type: checkboxes
    id: target-audience
    attributes:
      label: 👥 Target Audience
      description: Who would benefit from this feature?
      options:
        - label: Students (academic writing)
        - label: Professionals (business communication)
        - label: Content creators (articles, blogs)
        - label: Developers (code documentation)
        - label: Researchers (technical papers)
        - label: Educators (teaching materials)
        - label: Translators (multilingual content)
        - label: Arabic speakers specifically
        - label: Bilingual users (Arabic + English)
        - label: Technical writers
        - label: Social media managers
        - label: All users

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Any other information about this feature request
      placeholder: |
        - Related issues or discussions
        - Similar features in other tools
        - Research or articles supporting this need
        - Community feedback you've received
        - How this differs from/enhances current modes:
          • Fix, Improve, Rewrite modes
          • Answer, Summarize modes
          • Translate, Simplify modes
          • Longer, Shorter modes
          • Prompter mode
          • Formalize, Casual modes
          • Email, Bullets modes
          • Focus, Technical modes
          • Creative, Academic modes

  - type: textarea
    id: implementation
    attributes:
      label: 🔧 Implementation Ideas (Optional)
      description: Any thoughts on how this could be implemented?
      placeholder: |
        If you have technical ideas or suggestions:
        - UI/UX considerations
        - How it would integrate with existing modes
        - API requirements or considerations
        - Language-specific requirements
        - Performance considerations
        
        Note: This is optional - just describe the need and we'll handle the technical details!

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: Please confirm before submitting
      options:
        - label: I have searched existing feature requests for duplicates
          required: true
        - label: This feature aligns with the tool's purpose
          required: true
        - label: I have provided clear use cases and benefits
          required: true
        - label: I understand this is a request, not a guarantee
          required: true
